### ISSUE TITLE
Firefox support

### ISSUE THREAD

**Issue by psukys** [shumail92/COOKorBOOK#16]
Currently we only run tests on chrome. Maybe we should consider adding firefox aswell? This would include adding `karma-firefox-launcher` npm module in development, dependencies in protractor , and `firefox` package in travis.

**Comment by shumail92** [comment]
@psukys We aren't really focusing on writing unit tests atm. These are the default unit tests. 
But if we'll have time later on, we should add but instead of unit test, I would say we should go for e2e.

**Comment by shumail92** [comment]
not needed
