### ISSUE TITLE
Come up with better color scheme & remove shadows

### ISSUE THREAD

**Issue by shumail92** [shumail92/COOKorBOOK#19]
I think we should perhaps look into a better color swatch.
Orange & then white on orange doesn't look very appealing and user friendly as well like currently in nav menu and elsewhere.

In this way, we won't need shadows and shadows behind divs & texts aren't in practice anymore.

Let's discuss the possible options.

**Comment by loldemort** [comment]
Sure, I just went for it when making the mockups to make something fast

**Comment by psukys** [comment]
I find the navbar colour palette could be better.

While I do agree that shadows are a styling legacy, making the elements visible/readable on top of an image might be a tricky task. I guess, we could apply a blur or some fade filter on the image to replace shadows.
